analyzer:
  exclude:
  strong-mode:
    implicit-dynamic: true
    implicit-casts: false
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    close_sinks: false
    comment_references: false
    one_member_abstracts: false